//import icons
// @ts-ignore: Cannot find module or type declarations for side-effect import of 'bootstrap-icons/font/bootstrap-icons.css'.
import 'bootstrap-icons/font/bootstrap-icons.css' ;

//import bootstap
// @ts-ignore: Cannot find module or type declarations for side-effect import of 'bootstrap/dist/css/bootstrap.min.css'.
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import {EB_Garamond } from "next/font/google";
// @ts-ignore: Cannot find module or type declarations for side-effect import of './variables.css'.
import './variables.css';
// @ts-ignore: Cannot find module or type declarations for side-effect import of './globals.css'.
import "./globals.css";

const ebGaramond = EB_Garamond({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.className} ${ebGaramond.style} `}>
        {children}
      </body>
    </html>
  );
}
